services:
  backend:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"
    environment:
      - UVICORN_RELOAD=true
    volumes:
      - .:/app
    tty: true